import type { ThemeDefinition } from 'vuetify'

export const ScriptorDarkTheme: ThemeDefinition = {
  dark: true,
  colors: {
    primary: '#0A84FF',
    secondary: '#5E5CE6',
    accent: '#00D4AA',
    background: '#0A0A1A',
    surface: '#141428',
    'surface-variant': '#1E1E3A',
    'on-surface': '#FFFFFF',
    'on-surface-variant': '#B0B0C8',
    error: '#FF3B30',
    info: '#0A84FF',
    success: '#34C759',
    warning: '#FF9500',
    border: '#2A2A4A',
    'border-light': '#3A3A5A',
    inputBorder: '#4A4A6A',
    containerBg: '#0F0F20',
    primaryText: '#FFFFFF',
    secondaryText: '#B0B0C8',
    lightprimary: '#1A3A5A',
    lightsecondary: '#2A2A5A',
    lightsuccess: '#1A3A2A',
    lighterror: '#3A1A1A',
    lightwarning: '#3A3A1A',
    codeBg: '#1A1A2E',
    preBg: '#12122A',
    code: '#E0E0F0',
    chatMessageBubble: '#1E2A3A',
    mcpCardBg: '#1A1A2E',
    overlay: '#000000AA',
    gray100: '#1A1A2A',
    primary200: '#3A6AAA',
    secondary200: '#6A6AAA',
  },
  variables: {
    'border-color': '#2A2A4A',
    'border-opacity': 1,
    'high-emphasis-opacity': 1,
    'medium-emphasis-opacity': 0.7,
    'disabled-opacity': 0.5,
    'idle-opacity': 0.1,
    'hover-opacity': 0.08,
    'focus-opacity': 0.12,
    'selected-opacity': 0.12,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.16,
    'dragged-opacity': 0.08,
    'shadow-key-umbra-opacity': 0.2,
    'shadow-key-penumbra-opacity': 0.14,
    'shadow-ambient-opacity': 0.12,
  }
}

export const ScriptorLightTheme: ThemeDefinition = {
  dark: false,
  colors: {
    primary: '#007AFF',
    secondary: '#5856D6',
    accent: '#00C4AA',
    background: '#F5F5F7',
    surface: '#FFFFFF',
    'surface-variant': '#F0F0F5',
    'on-surface': '#1D1D1F',
    'on-surface-variant': '#6E6E73',
    error: '#FF3B30',
    info: '#007AFF',
    success: '#34C759',
    warning: '#FF9500',
    border: '#E5E5EA',
    'border-light': '#F0F0F5',
    inputBorder: '#C7C7CC',
    containerBg: '#FAFAFC',
    primaryText: '#1D1D1F',
    secondaryText: '#6E6E73',
    lightprimary: '#E8F4FF',
    lightsecondary: '#EDEBFF',
    lightsuccess: '#E8FCF0',
    lighterror: '#FFE8E8',
    lightwarning: '#FFF8E8',
    codeBg: '#F5F5F7',
    preBg: '#FAFAFA',
    code: '#1D1D1F',
    chatMessageBubble: '#E7EBF4',
    mcpCardBg: '#F0F4FF',
    overlay: '#FFFFFFAA',
    gray100: '#FAFAFA',
    primary200: '#90CAF9',
    secondary200: '#B8B8E8',
  },
  variables: {
    'border-color': '#E5E5EA',
    'border-opacity': 1,
    'high-emphasis-opacity': 1,
    'medium-emphasis-opacity': 0.7,
    'disabled-opacity': 0.5,
  }
}
